// Optional browser QA: install Playwright or set NODE_PATH to an existing installation.
// The Java game itself needs no npm dependencies.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.PW_CHANNEL || 'msedge'});
  const errors=[];const dir=path.join(__dirname,'../test-results');fs.mkdirSync(dir,{recursive:true});
  const desktop=await browser.newContext({viewport:{width:1440,height:1150}}),mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
  const host=await desktop.newPage(),guest=await mobile.newPage();
  for(const p of [host,guest])p.on('pageerror',e=>errors.push(e.message));
  try{
    await host.goto('http://localhost:3000');await host.locator('.build-card').first().waitFor();
    await host.screenshot({path:path.join(dir,'desktop-welcome.png'),fullPage:true});
    await guest.goto('http://localhost:3000');await guest.locator('.build-card').first().waitFor();
    assert.equal(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile has no horizontal overflow');
    await guest.screenshot({path:path.join(dir,'mobile-welcome.png'),fullPage:true});
    await host.locator('#name').fill('Autumn');await host.locator('#create').click();await host.locator('#code').filter({hasText:/[A-F0-9]{5}/}).waitFor();const code=await host.locator('#code').innerText();
    await guest.locator('#name').fill('<b>Sprout</b>');await guest.locator('[data-skin="scarecrow"]').click();await guest.locator('#room-code').fill(code);await guest.locator('#join-form button').click();await guest.locator('#room-panel').waitFor({state:'visible'});
    await host.locator('#player-count').filter({hasText:'2 / 8'}).waitFor();assert.equal(await host.locator('#roster b').count(),0,'Player names are rendered as text');
    await host.locator('#ready').click();await guest.locator('#ready').click();await host.locator('#start:not([disabled])').waitFor();await host.locator('#start').click();await host.locator('#phase-label').filter({hasText:'DUSK · TIME TO PLANT'}).waitFor();
    await guest.locator('#phase-label').filter({hasText:'DUSK · TIME TO PLANT'}).waitFor();
    const farm=await host.locator('#farm').boundingBox();
    await host.mouse.move(farm.x+farm.width*.5,farm.y+farm.height*.4);await host.mouse.down({button:'right'});await host.mouse.move(farm.x+farm.width*.5-65,farm.y+farm.height*.4+25,{steps:5});await host.mouse.up({button:'right'});
    await host.waitForFunction(()=>document.getElementById('farm').dataset.following==='false');
    const projection=await host.locator('#farm').evaluate(c=>({x:+c.dataset.cameraX,y:+c.dataset.cameraY,w:+c.dataset.viewWidth}));
    await host.mouse.click(farm.x+farm.width/2+(1200-projection.x)*farm.width/projection.w,farm.y+farm.height/2+(700-projection.y)*farm.width/projection.w);
    await host.locator('[data-type="cannon"]:not([disabled])').waitFor();await host.locator('[data-type="cannon"]').click();await guest.locator('#seeds').filter({hasText:'180'}).waitFor();
    await host.locator('#plot-detail').filter({hasText:'Pumpkin cannon'}).waitFor();await host.locator('#upgrade').click();await guest.locator('#seeds').filter({hasText:'150'}).waitFor();
    await guest.reload();await guest.locator('#room-panel').waitFor({state:'visible'});await guest.locator('#phase-label').filter({hasText:'DUSK · TIME TO PLANT'}).waitFor();assert.equal(await guest.locator('#code').innerText(),code,'Reload resumes same room');
    await host.locator('#help').click();await host.locator('#help-dialog').waitFor({state:'visible'});await host.locator('.dialog-close-button').click();
    await guest.locator('#touch-controls').waitFor({state:'visible'});
    const pad=await guest.locator('#touch-controls').boundingBox(),board=await guest.locator('#farm').boundingBox();assert.ok(pad.y>=board.y&&pad.y+pad.height<=board.y+board.height,'Mobile movement controls and farm fit together on screen');
    await host.screenshot({path:path.join(dir,'desktop-game.png'),fullPage:true});await guest.screenshot({path:path.join(dir,'mobile-game.png'),fullPage:true});
    const solo=await desktop.newPage();solo.on('pageerror',e=>errors.push(e.message));await solo.goto('http://localhost:3000');
    await solo.getByRole('button',{name:'Play single player'}).click();await solo.locator('#phase-label').filter({hasText:'TIME TO PLANT'}).waitFor();
    assert.equal(await solo.locator('#ready').isVisible(),false,'Solo skips readiness');assert.equal(await solo.locator('.room-code-line').isVisible(),false,'Solo hides room code');
    await solo.locator('#begin-night').click();await solo.locator('#phase-label').filter({hasText:'WAVE 1'}).waitFor();
    await solo.reload();await solo.locator('#phase-label').filter({hasText:'WAVE 1'}).waitFor();
    await solo.locator('#restart-solo').click();await solo.locator('#phase-label').filter({hasText:'TIME TO PLANT'}).waitFor();
    await solo.locator('#farm').focus();
    const canvas=solo.locator('#farm');const rect=await canvas.boundingBox();
    const before=await canvas.evaluate(c=>({x:+c.dataset.cameraX,y:+c.dataset.cameraY}));
    const getPlayer=()=>solo.evaluate(async()=>{const r=await fetch('/api/resume',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+sessionStorage.getItem('pumpkin-token')},body:'{}'});const d=await r.json();return d.state.players.find(p=>p.id===d.id);});
    const playerBefore=await getPlayer();
    await solo.mouse.move(rect.x+rect.width*.55,rect.y+rect.height*.45);await solo.mouse.down({button:'right'});await solo.mouse.move(rect.x+rect.width*.55+130,rect.y+rect.height*.45+70,{steps:8});await solo.mouse.up({button:'right'});
    await solo.waitForFunction(()=>document.getElementById('farm').dataset.following==='false');
    const after=await canvas.evaluate(c=>({x:+c.dataset.cameraX,y:+c.dataset.cameraY}));assert.ok(after.x<before.x-50&&after.y<before.y-25,'Right drag pans world');
    const playerAfter=await getPlayer();assert.equal(playerAfter.x,playerBefore.x,'Right drag does not move player');assert.equal(playerAfter.y,playerBefore.y,'Right drag does not move player');
    await solo.keyboard.press('Space');await solo.waitForFunction(()=>document.getElementById('farm').dataset.following==='true');
    const centered=await canvas.evaluate(c=>({x:+c.dataset.cameraX,y:+c.dataset.cameraY}));assert.ok(Math.abs(centered.x-playerAfter.x)<2&&Math.abs(centered.y-playerAfter.y)<2,'Space centers on character');
    for(const id of ['plant-hud','solo-tools','mission','touch-controls','toast','vote-dialog','result-dialog'])assert.equal(await solo.locator('#'+id).evaluate(e=>!!e.closest('.game-stage')),true,id+' inside game');
    await solo.locator('#open-charms').click();await solo.locator('#charm-menu').waitFor({state:'visible'});await solo.screenshot({path:path.join(dir,'charms-menu.png'),fullPage:true});await solo.locator('#close-charms').click();
    await solo.screenshot({path:path.join(dir,'single-player.png'),fullPage:true});
    assert.deepEqual(errors,[],'No browser runtime errors');
    console.log('PASS: desktop/mobile rendering, two-client room, safe names, ready/start, shared build/upgrade spending, reload reconnect, help dialog, solo restart, build after panning, right-drag camera, Space recenter, in-game HUD and charms menu.');
    console.log('Screenshots: '+dir);
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
